#:import RESOURCES resources.RESOURCES

<MenuButton@Button>
    font_size: "40dp"
    font_name: "assets/CascadiaCode.ttf"


<MainLabel>:
    color: "black"
    font_name: "assets/CascadiaCode.ttf"
    canvas.before:
        Color:
            rgba:(0.6, 0.7, 0.85, 1)
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [dp(10)]


<MainImage>:
    size_hint: (0.1, 0.1)
    fit_mode: 'contain'
    size_hint_x: 0.4
    pos_hint: {'center_y': 0.5}
    size_hint_y: None
    height: dp(50)


<BoxRow>:
    size_hint_y: None
    height: dp(50)
    spacing: dp(10)
    MainLabel:
        text: root.product_name
    MainLabel:
        text: root.product_price
    MainLabel:
        text: root.product_quantity
    MainLabel:
        text: root.product_volume
    MainImage:
        source: RESOURCES[root.product_name]
    CheckBox:
        on_active: root.on_checkbox_active(self)
        active: root.cb_active


<BasketRow>:
    size_hint_y: None
    height: dp(50)
    spacing: dp(10)
    MainLabel:
        text: root.product_name
    MainLabel:
        text: root.product_price
    MainLabel:
        text: root.quantity_box
    MainLabel:
        text: root.box_count
    MainImage:
        source: RESOURCES[root.product_name]


<BasketItemScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "20dp", "10dp"
        spacing: "8dp"

        Button:
            text: "< Назад"
            size_hint: None, None
            size: "120dp", "50dp"
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            on_press: root.goto_basket()

        Image:
            source: root.product_image
            fit_mode: "contain"
            size_hint_y: None
            height: "160dp"

        MainLabel:
            id: text_product
            text: root.product_name
            size_hint: (None, None)
            size: (dp(180), dp(45))
            pos_hint: {"center_x": 0.5}

        MainLabel:
            text: "Продуктов в коробке: " + root.quantity_box
            size_hint: (None, None)
            size: (dp(260), dp(40))
            pos_hint: {"center_x": 0.5}

        MainLabel:
            text: "Коробок:"
            size_hint: (None, None)
            size: (dp(150), dp(35))
            pos_hint: {"center_x": 0.5}

        BoxLayout:
            size_hint_y: None
            height: "70dp"
            spacing: "15dp"
            padding: "40dp", 0

            Button:
                text: "-"
                size_hint: None, None
                size: "65dp", "65dp"
                background_normal: ""
                background_color: 0.8, 0.2, 0.2, 1
                radius: [32]
                on_press: root.delete_quantity()

            TextInput:
                id: box_input
                text: root.box_count
                multiline: False
                input_filter: "int"
                font_size: "24sp"
                halign: "center"
                on_text: root.set_boxes_manual(self.text)

            Button:
                text: "+"
                size_hint: None, None
                size: "65dp", "65dp"
                background_normal: ""
                background_color: 0.2, 0.7, 0.2, 1
                radius: [32]
                on_press: root.add_quantity()

        Widget:
            size_hint_y: 1



<MenuScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 80
        Label:
            text: "Склад"
            font_size: "40sp"
            color: (0.15, 0.15, 0.15, 1)
            font_name: "assets/CascadiaCode.ttf"
            canvas.before:
                Color:
                    rgba: (0.85, 0.87, 0.90, 1)
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(10)]
        Image:
            source: 'assets/images/logo.png'
            fit_mode: 'cover'
        MenuButton:
            text: "Открыть"
            on_press: root.goto_main()

            background_normal: ""
            background_down: ""
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: (0.11, 0.31, 0.85, 1) if self.state == 'normal' else (0.15, 0.39, 0.92, 1)

                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(10)]


<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            size_hint_y: None
            height: "56dp"
            padding: "10dp", "8dp"
            spacing: "10dp"

            Button:
                text: "Меню"
                size_hint: None, None
                size: "100dp", "40dp"
                background_normal: ""
                background_color: 0.3, 0.3, 0.3, 1
                on_press: root.goto_main()

            Widget:

            Button:
                text: "Корзина"
                size_hint: None, None
                size: "120dp", "40dp"
                background_normal: ""
                background_color: 0.11, 0.31, 0.85, 1
                on_press: root.goto_basket()

        BoxLayout:
            size_hint_y: None
            height: "56dp"
            padding: "10dp", "8dp"
            spacing: "10dp"
            Widget:
                size_hint_x: 0.1
            Label:
                text: "Название:"
            Widget:
                size_hint_x: 0.3
            Label:
                text: "Количиство:"
            Widget:
                size_hint_x: 0.1
            Label:
                text: "Цена:"
            Label:
                text: "Объём:"
            Widget:
                size_hint_x: 1
            Widget:
                size_hint_x: 1
                
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            GridLayout:
                id: main_container
                cols: 1
                row_default_height: 40
                size_hint_y: None
                height: self.minimum_height
                padding: '20dp'
                spacing: '6dp'


<ProductScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "20dp", "10dp"
        spacing: "8dp"

        Button:
            text: "< Назад"
            size_hint: None, None
            size: "120dp", "50dp"
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            on_press: root.goto_main()

        Image:
            source: root.product_image
            fit_mode: "contain"
            size_hint_y: None
            height: "160dp"

        MainLabel:
            id: text_product
            text: root.product_name
            size_hint: (None, None)
            size: (dp(180), dp(45))
            pos_hint: {"center_x": 0.5}

        MainLabel:
            id: text_quantity
            text: root.product_quantity
            size_hint: (None, None)
            size: (dp(100), dp(45))
            pos_hint: {"center_x": 0.5}

        BoxLayout:
            size_hint_y: None
            height: "70dp"
            spacing: "15dp"
            padding: "60dp", 0

            Button:
                text: "+"
                size_hint: None, None
                size: "65dp", "65dp"
                background_normal: ""
                background_color: 0.2, 0.7, 0.2, 1
                radius: [32]
                on_press: root.add_quantity()

            Widget:
                size_hint_x: 1

            Button:
                text: "-"
                size_hint: None, None
                size: "65dp", "65dp"
                background_normal: ""
                background_color: 0.8, 0.2, 0.2, 1
                radius: [32]
                on_press: root.delete_quantity()

        Button:
            text: "Delete"
            size_hint: None, None
            size: "150dp", "55dp"
            pos_hint: {"center_x": 0.5}
            background_normal: ""
            background_color: 0.5, 0.5, 0.5, 1
            on_press: root.delete_product()

        Widget:
            size_hint_y: 1


<BasketScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: "20dp", "10dp"
        spacing: "8dp"

        Button:
            text: "< Назад"
            size_hint: None, None
            size: "120dp", "50dp"
            background_normal: ""
            background_color: 0.3, 0.3, 0.3, 1
            on_press: root.goto_main()

        BoxLayout:
            size_hint_y: None
            height: "36dp"
            spacing: "10dp"
            padding: "20dp", 0

            Label:
                text: "Товар"
            Label:
                text: "Цена"
            Label:
                text: "В коробке"
            Label:
                text: "Коробок"
            Widget:
                size_hint_x: 0.4

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            GridLayout:
                id: basket_container
                cols: 1
                row_default_height: 40
                size_hint_y: None
                height: self.minimum_height
                padding: '20dp'
                spacing: '6dp'
